### ISSUE TITLE
.summary method problems

### ISSUE THREAD

**Issue by barty5260** [ibaris/VaR#9] opened 2023-06-17 22:50 UTC
Hi @ibaris, it seems like I am having some problems accesing the .summary method. I have attached my output below.

I have checked using Readme parameters to check the error and it has persisted. I did import the functions directly from src.

![image](https://github.com/ibaris/VaR/assets/62222839/d444c089-492f-410a-a319-653f7724a414)

**Comment by ibaris** [comment] 2023-06-18 03:29
Okay. That is a weird one. I can not reproduce this error, since a pandas DataFrame have a method called `append` (see [here](https://pandas.pydata.org/pandas-docs/version/1.3/reference/api/pandas.DataFrame.append.html). What is your pandas version?

**Comment by barty5260** [comment] 2023-06-18 08:44
Hmm. I am using pandas 2.0.2, as specified by reqs.txt. According to [mozway, Stackoverflow](https://stackoverflow.com/questions/75956209/dataframe-object-has-no-attribute-append), append was removed with pandas 2.0.

I would recommend you to freeze the requirements of your virtual environment with the exact version of each of the packages the repo uses. That way there should be no confusion. 👍

**Comment by ibaris** [comment] 2023-06-18 20:35
Good One! I change the `append` method in favor of ` pd.concat`. Thank you very much for your time and effort!

**Comment by barty5260** [comment] 2023-06-18 20:57
That sounds good. As I said before, if you feel like there are other parts of the code that could become deprecated when updating packages, you could use `pip freeze > requirements.txt` so the package versions are specified. Thank you for looking into every issue so quickly!

**Comment by ibaris** [comment] 2023-06-19 12:59
Yeah, that is a great idea. I will not close this issue until I change the requirements.

**Closed** 2023-07-02 03:51 UTC
